# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

_defaults: &defaults
    docker:
      - image: circleci/golang:1.11

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
      - run:
          name: Building and testing
          command: |
            go build ./...
            go get -u github.com/onsi/ginkgo/ginkgo
            go get -u github.com/loongy/covermerge
            GOMAXPROCS=1 CI=true /go/bin/ginkgo -v --race \
            --cover --coverprofile coverprofile.out ./...
            /go/bin/covermerge block/coverprofile.out \
              cmd/node/coverprofile.out \
              replica/coverprofile.out \
              sig/coverprofile.out \
              sig/ecdsa/coverprofile.out \
              supervisor/coverprofile.out > coverprofile.out
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
            - "/go/bin"

workflows:
  version: 2.1
  build:
    jobs:
    - build
